# Generated by Django 3.2.16 on 2025-05-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_auto_20250410_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='posts/')),
                ('is_private', models.BooleanField(default=False, help_text='Если отмечено, журнал доступен только автору', verbose_name='Приватный пост')),
                ('pin_code', models.CharField(blank=True, default=None, help_text='Необязательный код для доступа к посту (4-6 цифр)', max_length=128, null=True, verbose_name='Защитный PIN-код')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified', 'title'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Если отмечено, пост доступен только автору', verbose_name='Приватный пост'),
        ),
        migrations.AddField(
            model_name='post',
            name='journal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.journal'),
            preserve_default=False,
        ),
    ]
