# Generated by Django 3.2.16 on 2025-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20250515_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
