# Generated by Django 3.2 on 2025-05-17 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_alter_journal_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
